open_steam_mokodesk_index:
    path:  /
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:index }

open_steam_mokodesk_login:
    path:  /login/
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:login }

open_steam_mokodesk_logout:
    path:  /logout/
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:logout }

open_steam_mokodesk_data:
    path:  /data/
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:data }

open_steam_mokodesk_folder:
    path:  /folder/
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:folder }

open_steam_mokodesk_update:
    path:  /update/
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:update }

open_steam_mokodesk_upload_file:
    path:  /upload/
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:upload }

open_steam_mokodesk_edit:
    path:  /edit/
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:edit }

open_steam_mokodesk_getpath:
    path:  /get/path/{path}
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:getpath }
    requirements:
        path: ".+"

open_steam_mokodesk_get:
    path:  /get/{id}
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:get }
    requirements:
        id: \d+

open_steam_mokodesk_thumbnail:
    path:  /thumbnail/{id}/{width}/{height}
    defaults: { _controller: OpenSteamMokodeskBundle:Mokodesk:thumbnail }
    requirements:
        id: \d+
        width: \d+
        height: \d+