parameters:
#    open_steam_mokodesk.example.class: OpenSteam\MokodeskBundle\Example

services:
#    open_steam_mokodesk.example:
#        class: %open_steam_mokodesk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
