parameters:
#    open_steam_mokodesk.example.class: OpenSteam\MokodeskBundle\Example

services:
#    open_steam_mokodesk.example:
#        class: %open_steam_mokodesk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    open_steam_mokodesk.backtrace_logger_listener:
        class: OpenSteam\MokodeskBundle\EventListener\BacktraceLoggerListener
        tags:
            - {name: "monolog.logger", channel: "backtrace"}
            - {name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException"}
        arguments:
            - @logger
